### ISSUE TITLE
Select Next Thing in Same Square Button breaks HeightOffsets on Building_Storage

### ISSUE THREAD

**Issue by CBornholdt** [Varisha84/ExtendedInspectData#6]
Clicking on the Select Next Thing in Same Square button on a Building_Storage can break the HeightOffset calculation on the child panes. This is because the MainTabWindow_Inspect.SelectNextInCell() method does not call the RequestedTabSize method when switching the selected item.

**Comment by Varisha84** [comment]
Thanks for contributing to my mod. Sry for seeing it late, Merged it, so it is included in B19 release v.1.1.19.0
